// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNlen91m6zNNU6rjPSj21_Xtt8XGcJ4A',
    appId: '1:157007901610:web:89175efb24b84106fd71d3',
    messagingSenderId: '157007901610',
    projectId: 'pivotal-racer-496313-v2',
    authDomain: 'pivotal-racer-496313-v2.firebaseapp.com',
    storageBucket: 'pivotal-racer-496313-v2.firebasestorage.app',
    measurementId: 'G-VP1D4JD8P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqtQg_raesE7Dsk0D1J1q5a8_2xCv6oaM',
    appId: '1:157007901610:android:1b75820d41509ca2fd71d3',
    messagingSenderId: '157007901610',
    projectId: 'pivotal-racer-496313-v2',
    storageBucket: 'pivotal-racer-496313-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DVmRjmUCarPHEXrt9v-psFMuUWYiIqU',
    appId: '1:157007901610:ios:c0d5b36a4fea29d4fd71d3',
    messagingSenderId: '157007901610',
    projectId: 'pivotal-racer-496313-v2',
    storageBucket: 'pivotal-racer-496313-v2.firebasestorage.app',
    iosBundleId: 'com.example.escolaconecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Dvl3BVI3OYa5pGSPROZ3t0p0ZWu2YNI',
    appId: '1:188900793025:ios:021a4b1465006eb40bd240',
    messagingSenderId: '188900793025',
    projectId: 'teste-app-i-s-a-m-rwxibd',
    storageBucket: 'teste-app-i-s-a-m-rwxibd.firebasestorage.app',
    iosBundleId: 'com.example.escolaconecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy3MgUBI4XweNkt9OHgXfWxTMxOcSTQhw',
    appId: '1:188900793025:web:b9ac00e459725c140bd240',
    messagingSenderId: '188900793025',
    projectId: 'teste-app-i-s-a-m-rwxibd',
    authDomain: 'teste-app-i-s-a-m-rwxibd.firebaseapp.com',
    storageBucket: 'teste-app-i-s-a-m-rwxibd.firebasestorage.app',
  );

}